name: Fetch Appstore Info 

on:
 schedule:
     - cron: "0/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: "14.x"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - run: gem install bundler:2.1.4
      - run: bundle install
      - run: npm install 
      - run: node Sources/check_status.js
        env: 
          PRIVATE_KEY: $PRIVATE_KEY
          KEY_ID: $KEY_ID
          ISSUER_ID: $ISSUER_ID
          BUNDLE_ID: $BUNDLE_ID
          SLACK_WEBHOOK: $SLACK_WEBHOOK
          LANGUAGE: "ko"
      - name: push
        uses: github-actions-x/commit@v2.7
        with:
          github-token: $TOKEN
          push-branch: 'master'
          commit-message: 'Store Appstore Info'
          force-add: 'true'
          files: store.db
          name: sweeepty
          email: sy.lee@iconloop.com
